import ForgotPasswordPage from '@/page/forgot-password'
import React from 'react'
export const metadata = {
    title: "forgot password",
    description: "Generated by Queary Boat",
};
const ForgotPassword = () => {
    return (
        <ForgotPasswordPage />
    )
}

export default ForgotPassword
