const SECRETS = {
    ENVIRONMENT: process.env.NEXT_PUBLIC_ENVIRONMENT,
    LOCAL_API_URL: process.env.NEXT_PUBLIC_APP_LOCAL_API_URL,
    PRODUCTION_API_URL: process.env.NEXT_PUBLIC_APP_PRODUCTION_API_URL,
    LOCAL_SOCKET_URL: process.env.NEXT_PUBLIC_APP_LOCAL_SOCKET_URL,
    PRODUCTION_SOCKET_URL: process.env.NEXT_PUBLIC_APP_LOCAL_SOCKET_URL,
}
export default SECRETS