import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import '@/style/style.scss';
import App from './App';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Queary Boat",
  description: "Generated by Queary Boat",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <App children={children} />
      </body>
    </html >
  );
}
