import Link from 'next/link';
import React from 'react'
export const metadata = {
  title: "loading...",
  description: "Generated by Queary Boat",
};
const page = () => {
  return (
    <div>
      <Link href="/login">Login page</Link> <br />
      <Link href="/chat">Chat page</Link> <br />
    </div>
  )
}

export default page