import LoginPage from '@/page/login'
import React from 'react'
export const metadata = {
    title: "Login at Queary Boat",
    description: "Generated by Queary Boat",
};
const Login = () => {
    return (
        <LoginPage />
    )
}

export default Login
