import SignUpPage from '@/page/sign-up';
import React from 'react'
export const metadata = {
    title: "Create an  Account",
    description: "Generated by Queary Boat",
};
const SignUp = () => {
    return (
        <SignUpPage />
    )
}

export default SignUp
